pluginManagement {
    repositories {
        // aliyun first: this box gets rate-limited (429) by Maven Central
        maven { url = 'https://maven.aliyun.com/repository/central' }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'vfxlab-probe'
